development:
  adapter: sqlite3
  database: scrapper_devel
  pool: 25
  username: root
  password:
  encoding: utf8
test:
  adapter: sqlite3
  database: scrapper_test
  pool: 25
  username: root
  password:
  encoding: utf8
